---
toc: false
---

## How to use this book

This book contains the materials for the WEHI RNA-seq course. It follows on from the WEHI R programming course, so it is recommended that you have completed that course or have equivalent R programming experience before undertaking this course.

<!-- ### Session 5: RNA-seq part 1
In this session, we introduce RNA-seq data analysis using the limma-voom workflow. You will learn how to construct `DGEList` objects for the `edgeR` package, filter lowly expressed genes, normalize data for library size and RNA composition, perform exploratory analysis with multidimensional scaling (MDS) plots, and extract data from Bioconductor objects for visualization with `ggplot2`. The dataset comprises gene expression from three mouse mammary gland cell populations (basal, luminal progenitor, and mature luminal cells).

### Session 6: RNA-seq part 2
This session completes the RNA-seq analysis workflow. You will learn how to construct design and contrast matrices for specifying statistical comparisons, use the `voom()` function to model the mean-variance relationship in RNA-seq data, fit gene-wise linear models with empirical Bayes moderation, perform statistical testing to identify differentially expressed genes, create publication-quality MA plots to visualize results, and export analysis results to files for sharing or publication. -->

Code is shown in blue, with the output below it in grey, just like it would show up in the R console.

```{r}
# This is an R code block
# You can run this code by copying it into the R console
1 + 1
```

You can run the code yourself by copying it (using the copy button in the top right of the code block) and pasting it into R on your computer.

## Acknowledgements
We would like to thank Kerry Ko, Brendan Ansell and the WEHI education office for their work in organising and facilitating this course. We would also like to thank all of our instructors and tutors for making this course possible.

We acknowledge that this course is prepared and delivered on the unceded land of the Wurundjeri people of the Kulin Nation. We pay our respects to their Elders past, present, and emerging. We also acknowledge that sovereignty was never ceded, and that this always was and always will be Aboriginal land.
